### ISSUE TITLE
' remove <X-Cart>/var/run' does not work for 5.4.0

### ISSUE THREAD

**Issue by ildar-aim** [xcart/xcart-docs#68]
This issue is about <https://devs.x-cart.com/getting_started/creating-module.html> (source file: <https://github.com/xcart/xcart-docs/blob/master/_pages/devs_en/getting_started/creating-module.md>)

`Or just remove <X-Cart>/var/run directory and refresh any page.
`

**Comment by tony-sologubov** [comment]
Что здесь не так?

**Comment by ildar-aim** [comment]
я удаляю var/run и возникает ошибка 

```
[25-Mar-2019 11:38:52] Error (code: 0): Undefined method 'getAllOptions'. The method name must start with either findBy, findOneBy or countBy!
Server API: fpm-fcgi;
Request method: GET;
URI: /~aim/next/src/cart.php;
Backtrace:
#0 /home/aim/public_html/next/src/classes/XLite/Core/Config.php(73): Doctrine\ORM\EntityRepository->__call('getAllOptions', Array)
#1 /home/aim/public_html/next/src/classes/XLite/Core/Config.php(53): XLite\Core\Config->readFromDatabase(false)
#2 /home/aim/public_html/next/src/classes/XLite/Core/Config.php(30): XLite\Core\Config->readConfig()
#3 /home/aim/public_html/next/src/top.inc.php(33): XLite\Core\Config::getInstance()
#4 /home/aim/public_html/next/src/cart.php(14): require_once('/home/aim/publi...')
#5 {main}
```

через интерфейс все нормально

**Comment by tony-sologubov** [comment]
Давай в личке обсудим.

**Comment by miryamfv** [comment]
I need help please. I installed xcart5 on a subfolder /xcart5, after moving to the root folder following this guide:

https://kb.x-cart.com/general_setup/maintenance/moving_x-cart_to_another_location.html

I can't access the store any help is much appreciated

`[09-Jul-2020 16:53:07] Error (code: 0): Undefined method 'getAllOptions'. The method name must start with either findBy, findOneBy or countBy!
Server API: cgi-fcgi;
Request method: GET;
URI: /userfiles/kak-pravilno-sobrat-spinning-dlia-lovli-shchuki-6766.xml;
Backtrace: 
#0 /home1/skydivh6/public_html/glowfast/classes/XLite/Core/Config.php(88): Doctrine\ORM\EntityRepository->__call('getAllOptions', Array)
#1 /home1/skydivh6/public_html/glowfast/classes/XLite/Core/Config.php(68): XLite\Core\Config->readFromDatabase(false, false)
#2 /home1/skydivh6/public_html/glowfast/classes/XLite/Core/Config.php(32): XLite\Core\Config->readConfig(false, false)
#3 /home1/skydivh6/public_html/glowfast/classes/XLite/Core/Request.php(747): XLite\Core\Config::getInstance()
#4 /home1/skydivh6/public_html/glowfast/classes/XLite/Core/Request.php(562): XLite\Core\Request->getCookieSecure()
#5 /home1/skydivh6/public_html/glowfast/classes/XLite/Core/Request.php(850): XLite\Core\Request->setCookie('is_robot', 'cc995f76ea8fd14...')
#6 /home1/skydivh6/public_html/glowfast/classes/XLite/Logger.php(185): XLite\Core\Request->isBot()
#7 /home1/skydivh6/public_html/glowfast/classes/XLite/Logger.php(304): XLite\Logger->log('Warning: Cannot...', 4)
#8 [internal function]: XLite\Logger->registerPHPError(2, 'Cannot modify h...', '/home1/skydivh6...', 28, Array)
#9 /home1/skydivh6/public_html/glowfast/error_handler.php(28): header('Content-Type: t...', true, 500)
#10 /home1/skydivh6/public_html/glowfast/Includes/ErrorHandler.php(357): showErrorPage(0, 'Undefined metho...', '<!DOCTYPE html>...', 'ERROR_', 500)
#11 /home1/skydivh6/public_html/glowfast/Includes/ErrorHandler.php(454): Includes\ErrorHandler::showErrorPage(0, 'Undefined metho...')
#12 /home1/skydivh6/public_html/glowfast/cart.php(23): Includes\ErrorHandler::handleException(Object(BadMethodCallException))
#13 {main}`

**Comment by ildar-aim** [comment]
Hello,

please post a ticket here https://secure.x-cart.com/ in our Helpdesk
