### ISSUE TITLE
How to assign a membership level to user?  This basic question is not answered in this page.

### ISSUE THREAD

**Issue by kde35** [xcart/xcart-docs#70]
This issue is about <https://kb.x-cart.com/users/memberships/managing_user_membership_levels.html> (source file: <https://github.com/xcart/xcart-docs/blob/master/_pages/kb_en/users/memberships/managing_user_membership_levels.md>)

**Comment by tony-sologubov** [comment]
Hi,

This task is explained in the screenshot next to the following text
> From the drop-down list in the Membership field, select the membership level requested by the user.

Are you able to assign a membership level to a customer now?

Best,

Tony

**Comment by kde35** [comment]
Thank you very much, it works, but the page is misleading.  It gives impression that one can assign membership only to those who requested.  (But whichever level, not necessarily requested one...)
