### ISSUE TITLE
The tarfile is missing ARepo.php

### ISSUE THREAD

**Issue by kde35** [xcart/xcart-docs#74]
As the title indicates.  There are only classes/XLite/Module/XCExample/SearchRepoDemo/Main.php
classes/XLite/Module/XCExample/SearchRepoDemo/Model/Repo/Product.php
.phar/.metadata.bin
.hash

in the tar archive.

This issue is about <https://devs.x-cart.com/getting_started/working-with-database.html> (source file: <https://github.com/xcart/xcart-docs/blob/master/_pages/devs_en/getting_started/working-with-database.md>)

**Comment by tony-sologubov** [comment]
Thanks. I have corrected the article.
